name: Linting Formatting Unit and Integration Tests

on:
  pull_request:
    branch:
      - 'main' # This ensures these tests are run on pull requests that are open against the branch "main"

jobs:
  validate-code-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16.x] # If your app or package needs to be tested on multiple versions of node, you can specify multiple versions here and your workflow will be run on each one of them
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm i install --non-interactive
      - name: Run Unit and Integration tests
        run: |
          npn run test
